###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = kitty -e lf
$menu = rofi -show drun -config ~/.config/rofi/config.rasi


#################
### AUTOSTART ###
#################

exec-once = /usr/lib/gnome-keyring-daemon --start --components=secrets,pkcs11
exec-once = quickshell & hyprpaper & hypridle & swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = udiskie &


