# See https://wiki.hypr.land/Configuring/

source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/look-and-feel.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/windowrules.conf
