[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=purple-glass

[Wayland]
CompositorCommand=kwin_wayland --no-lockscreen

[X11]
ServerArguments=-nolisten tcp
