###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher


#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper & hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = systemctl --user start xdg-desktop-portal-hyprland
