##############################
### WINDOWS AND WORKSPACES ###
##############################

# Blur rules for layer surfaces
layerrule {
    name = blur-bar
    match:namespace = quickshell-bar
    blur = true
}

layerrule {
    name = blur-cc
    match:namespace = quickshell-cc
    blur = true
    ignore_alpha = 0.05
}

layerrule {
    name = blur-rofi
    match:namespace = rofi
    blur = true
}

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Default opacity for all apps
# Get window names with "hyprctl clients | grep class"

windowrule {
    name = default-opacity
    match:class = .*
    opacity = 0.80 0.70
}

# Override opacity on apps that cannot have opacity at all such as video players
windowrule {
    name = override-opacity
    match:class = ^(com.github.iwalton3.jellyfin-media-player|vlc|firefox|tv.plex.plex-bin)$
    opacity = 1.0
}

# Custom opacity for vscode for readability
windowrule {
    name = vscodium-opacity
    match:class = ^(codium|VSCodium|code-oss|Code)$
    opacity = 0.87
}
